Portfolio: preserve data in the browser
AlselwiAisha/AishaPortfolio pull request #14
Opened 2023-05-25 15:15 UTC by AlselwiAisha

### Description:

- Save the form data in the local storage of the browser.
- Fix linter errors.

2023-05-25 15:31 UTC, frank1738 reviewed
Hi @AlselwiAisha , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a pair programming project with only one contributor. Kindly also fix the conflict between the branches for your linters to run.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2023-05-26 09:38 UTC, aamirkhan2478 requested changes
Hi @AlselwiAisha , 

![](https://media2.giphy.com/media/t8YPf3ACKeouLzEIvr/giphy.gif?cid=ecf05e47k5uapdptg00nidbw3qaxx8iqgsusgaswci2c3uh1&rid=giphy.gif&ct=g)

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Highlights
✔️ Good Effort
✔️ Your design is good.
✔️ All linters passed

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-26 09:38 UTC, aamirkhan2478 commented on script.js
> +});
- [ ] I noticed when I submit the form then the data is saved in the `local storage` which is wrong you should implement the following interactions:
- When the user changes the content of any `input field`, the data is saved to the `local storage`. :+1: 
- When the user `loads` the page, if there is any data in the `local storage` the `input fields` are `pre-filled` with this data. :slightly_smiling_face:

2023-05-26 11:27 UTC, alexander16108 approved these changes
Hi @AlselwiAisha , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 ]

<img src="https://media2.giphy.com/media/3o7abB06u9bNzA8lu8/giphy.gif"/>

## Highlights
✅ Linters are passing
✅ Good commit history
✅ Good Pull Request description
✅ README looks professional
✅ Live version works correctly 🥇

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-26 11:38 UTC, merged